### ISSUE TITLE
Launch error on RPI2 - Trusty - Indigo : Permission denied

### ISSUE THREAD

**Issue by patrickpoirier51** [erlerobot/ros_erle_spider#3]
Trying to build ros_erle_spider from scratch with RaspberryPi2 + Bluetooth controler + Maestro 24

Env: RPI2 - Trusty -Indigo  (ROS tested OK on catkin_ws)

mkdir -p ~/spider_ws/src
cd ~/spider_ws/src
catkin_init_workspace
cd ..
catkin_make_isolated
source devel_isolated/setup.bash
cd src/
(git clone https://github.com/erlerobot/ros_erle_spider) === 
NOTE: JUST COPIED spider_code & spider_control & spider_description
cd ..
source devel_isolated/setup.bash
catkin_make_isolated

--Launch error----
ubuntu@ubuntu:~/spider_ws$ roslaunch spider_control spider_control.launch                            ... logging to /home/ubuntu/.ros/log/f49bb482-1699-11e6-863e-b827ebe0030e/roslaunch-ubuntu-2470.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 654, in _recurse_load
    n = self._node_tag(tag, context, ros_config, default_machine, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 406, in _node_tag
    self._param_tag(t, param_ns, ros_config, force_local=True, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 264, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/loader.py", line 489, in param_value
    p = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by LanderU** [comment]
Hi @patrickpoirier51,

you are using Ubuntu-Core?

**Comment by patrickpoirier51** [comment]
Yes , as the title show RPI2 - Trusty - Indigo
So it is Ubuntu 14.04 Lts for Arm ==Trusty

**Comment by patrickpoirier51** [comment]
Making Some progress, 
Stripped down the spider_control.launch file, just keeping the spider_control.yaml 
but still generate an error 
 Controller Spawner: Waiting for service controller_manager/load_controller
[WARN] [WallTime: 1462926238.484415] Controller Spawner couldn't find the expect                                  ed controller_manager ROS interface.

Is this launch file is for the Physical Spider or just for the Gazebo ?

Meanwhile I will continue testing the individual modules

**Comment by DaikiMaekawa** [comment]
I've never tried build this packages but anyway, your error looks like happened by you gave invalid value to <param>. I guess you got something error from xacro parser. https://github.com/erlerobot/ros_erle_spider/blob/master/spider_control/launch/spider_control.launch#L16

**Comment by DaikiMaekawa** [comment]
@patrickpoirier51 I found copied xacro code in local. https://github.com/erlerobot/ros_erle_spider/tree/master/spider_code/xacro

1. check spider_description path is available in your environment.
2. can you parse spider_gazebo.xacro by xacro.py without the launch file?
3. check local xacro package works fine or not.

**Comment by patrickpoirier51** [comment]
Thanks for the follow-up Daiki,
I am deconstructing the code because it is for Gazebo Simulation from a Workstation and not the Spider Code on the RPI. So I am loading stuff manually for the moment.
The xacro.py gave error,(http://stackoverflow.com/questions/24161476/subprocess-popen-simple-code-does-not-allow-me-to-perform-a-cd-change-directory)  so I updated these lines::
#this_dir = os.path.dirname(__file__)
this_dir=os.path.dirname(os.path.abspath(__file__))

Work In Progress

**Comment by patrickpoirier51** [comment]
Working now. You can close the issue
